[project]
name = "new-folder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    {name = "Muhammad Fahad Khakwani", email = "fahadyousufkhakwani@gmail.com"}
]
requires-python = ">=3.13"
dependencies = []
